### ISSUE TITLE
Update tableschema plugins to work with renamed core

### ISSUE THREAD

**Issue by roll** [frictionlessdata/implementations#11]
# Overview

In following to renaming `jsontableschema` to `tableschema` we should update plugins.

# Tasks

- [ ] https://github.com/frictionlessdata/jsontableschema-sql-py
- [ ] https://github.com/frictionlessdata/jsontableschema-bigquery-py
- [ ] https://github.com/frictionlessdata/jsontableschema-pandas-py

**Comment by roll** [comment]
@vshih
I've prioritized it but still it could take some time to address so for now prev1 could be used with plugins.

**Comment by vshih** [comment]
Okay thanks.  Would that be v0.10.1?

**Comment by roll** [comment]
MERGED
https://github.com/frictionlessdata/implementations/issues/22
