### ISSUE TITLE
Update storages to specs-v1 with FK support

### ISSUE THREAD

**Issue by roll** [frictionlessdata/implementations#22]
# Overview

The specifications v1 is released (https://blog.okfn.org/2017/09/05/frictionless-data-v1-0/) as well as Python libraries v1. So we need to updated `tableschema` plugins to work with updated core.

# Tasks

- [x] in following to renaming jsontableschema to tableschema we should update plugins
- [x] make all needed changes to support v1
- [x] ensure support for FK when possible
