### ISSUE TITLE
Implementations status

### ISSUE THREAD

**Issue by roll** [frictionlessdata/implementations#26]
# Frictionless Data Implementations

In a `requirements` section we list all required functionality. Then in per language sections we list **what's missed** for now. Not every missing thing should be implemented right now - some stuff (like foreign keys) could be backlogged for a while for some implementation. But in this document we're trying to draw the whole picture.

## Requirements

High-level requirements [reference]( http://specs.frictionlessdata.io/implementation/). It uses *italics* for requirements not directly mentioned in the implementation requirements document:

- **tableschema**
    - read and validate a table schema descriptor
    - create and edit a table schema descriptor
    - provide an API to interact with a table schema descriptor
    - infer a table schema descriptor from a supplied sample of data
    - validate a data source against the table schema descriptor, including in response to editing the descriptor
    - streaming and reading of a data source through a table schema with cast on iteration
    - save a table schema descriptor to a file path
    - *cover the latest changes in the spec such as `bareNumber`, `true/falseValues`, `string PK/FK` etc*
    - *support true data streaming*
    - *support all data constraints*
    - *support all data types*
- **datapackage**
    - read and validate a data package descriptor, including profile-specific validation via the registry of JSON Schemas
    - create and edit a data package descriptor, including methods to add and remove resources and validation after editing
    - provide an API to interact with a data package descriptor
    - streaming and reading of resources through a table schema with cast on iteration
    - save a data package descriptor to a file path
    - save a data package as a zip file on disc
    - read a zip file containing a data package
    - *cover the latest changes in the specs such as string/array for `path` etc*
    - *support for schema dereferencing before validation*
    - *support for multipart resources*
    - *support for csv dialects*

## Python

Repositories:

- [tableschema](https://github.com/frictionlessdata/tableschema-py)
- [datapackage](https://github.com/frictionlessdata/datapackage-py)

Maintainers:

- [Evgeny Karev](https://github.com/roll)

## JavaScript

Not implemented requirements:

- **datapackage**
    - save a data package as a zip file on disc - [#93](https://github.com/frictionlessdata/datapackage-js/issues/93)
    - read a zip file containing a data package - [#93](https://github.com/frictionlessdata/datapackage-js/issues/93)
    - *support for multipart resources* - [#79](https://github.com/frictionlessdata/datapackage-js/issues/79)
    - *support for csv dialects* - [#86](https://github.com/frictionlessdata/datapackage-js/issues/86)

Repositories:

- [tableschema](https://github.com/frictionlessdata/tableschema-js)
- [datapackage](https://github.com/frictionlessdata/datapackage-js)

Maintainers:

- [Evgeny Karev](https://github.com/roll)

## Ruby

Not implemented requirements:

- **datapackage**
    - save a data package as a zip file on disc - [#49](https://github.com/frictionlessdata/datapackage-rb/issues/49)
    - read a zip file containing a data package - [#49](https://github.com/frictionlessdata/datapackage-rb/issues/49)
    - *support for multipart resources* - [#37](https://github.com/frictionlessdata/datapackage-rb/issues/37)
    - *support for csv dialects* - [#51](https://github.com/frictionlessdata/datapackage-rb/issues/51)

Repositories:

- [tableschema](https://github.com/frictionlessdata/tableschema-rb)
- [datapackage](https://github.com/frictionlessdata/datapackage-rb)

Maintainers:

- [Evgeny Karev](https://github.com/roll)

## PHP

Not implemented requirements:

- **tableschema**
    - infer a Table Schema descriptor from a supplied sample of data - no stand-alone function - [#33](https://github.com/frictionlessdata/tableschema-php/issues/33)
    - *cover the latest changes in specs such as `bareNumber`, `true/falseValues`, `string PK/FK` etc* - [#34](https://github.com/frictionlessdata/tableschema-php/issues/34)
- **datapackage**
    - read a zip file containing a data package? - [#31](https://github.com/frictionlessdata/datapackage-php/issues/31)
    - *support for schema dereferencing before validation?* - [#37](https://github.com/frictionlessdata/datapackage-php/issues/37)
    - *support for multipart resources?* - [#33](https://github.com/frictionlessdata/datapackage-php/issues/33)
    - *support for csv dialects* - [#34](https://github.com/frictionlessdata/datapackage-php/issues/34)

Repositories:

- [tableschema](https://github.com/frictionlessdata/tableschema-php)
- [datapackage](https://github.com/frictionlessdata/datapackage-php)

Maintainers:

- [Ori Hoch](https://github.com/OriHoch)

## Java

Requirements to implement:

- **tableschema**
    - *support true data streaming* - it seems for now we read to memory in `this.data = this.reader.readAll()` - [#9](https://github.com/frictionlessdata/tableschema-java/issues/9)
    - *cover the latest changes in the spec such as `bareNumber`, `true/falseValues`, `string PK/FD`* - [#4](https://github.com/frictionlessdata/tableschema-java/issues/4)
- **datapackage**
    - read and validate a data package descriptor, including profile-specific validation via the registry of JSON Schemas - [#6](https://github.com/frictionlessdata/datapackage-java/issues/6)
    - create and edit a data package descriptor, including methods to add and remove resources and validation after editing - [#7](https://github.com/frictionlessdata/datapackage-java/issues/7)
    - provide an API to interact with a data package descriptor - [#8](https://github.com/frictionlessdata/datapackage-java/issues/8)
    - streaming and reading of resources through a table schema with cast on iteration - [#9](https://github.com/frictionlessdata/datapackage-java/issues/9)
    - save a data package descriptor to a file path - [#10](https://github.com/frictionlessdata/datapackage-java/issues/10)
    - save a data package as a zip file on disc - [#11](https://github.com/frictionlessdata/datapackage-java/issues/11)
    - read a zip file containing a data package - [#12](https://github.com/frictionlessdata/datapackage-java/issues/12)
    - *cover the latest changes in the specs such as string/array for `path` etc* - [#13](https://github.com/frictionlessdata/datapackage-java/issues/13)
    - *support for schema dereferencing before validation* - [#14](https://github.com/frictionlessdata/datapackage-java/issues/14)
    - *support for multipart resources* - [#15](https://github.com/frictionlessdata/datapackage-java/issues/15)
    - *support for csv dialects* - [#16](https://github.com/frictionlessdata/datapackage-java/issues/16)

Repositories:

- [tableschema](https://github.com/frictionlessdata/tableschema-java)
- [datapackage](https://github.com/frictionlessdata/datapackage-java)

Maintainers:

- [Georges Labrèche](https://github.com/georgeslabreche)

## Go

Not implemented requirements:

- **datapackage**
    - read and validate a data package descriptor, including profile-specific validation via the registry of JSON Schemas
    - create and edit a data package descriptor, including methods to add and remove resources and validation after editing
    - provide an API to interact with a data package descriptor
    - streaming and reading of resources through a table schema with cast on iteration
    - save a data package descriptor to a file path
    - save a data package as a zip file on disc
    - read a zip file containing a data package
    - *cover the latest changes in the specs such as string/array for `path` etc*
    - *support for schema dereferencing before validation*
    - *support for multipart resources*
    - *support for csv dialects*

Repositories:

- [tableschema](https://github.com/frictionlessdata/tableschema-go)
- [datapackage](https://github.com/frictionlessdata/datapackage-go)

Maintainers:

- [Daniel Fireman](https://github.com/danielfireman)

## R

Requirements to implement:

- **tableschema**
    - read and validate a table schema descriptor
    - create and edit a table schema descriptor
    - provide an API to interact with a table schema descriptor
    - infer a table schema descriptor from a supplied sample of data
    - validate a data source against the table schema descriptor, including in response to editing the descriptor
    - streaming and reading of a data source through a table schema with cast on iteration
    - save a table schema descriptor to a file path
    - *cover the latest changes in the spec such as `bareNumber`, `true/falseValues`, `string PK/FK` etc*
    - *support true data streaming*
- **datapackage**
    - read and validate a data package descriptor, including profile-specific validation via the registry of JSON Schemas
    - create and edit a data package descriptor, including methods to add and remove resources and validation after editing
    - provide an API to interact with a data package descriptor
    - streaming and reading of resources through a table schema with cast on iteration
    - save a data package descriptor to a file path
    - save a data package as a zip file on disc
    - read a zip file containing a data package
    - *cover the latest changes in the specs such as string/array for `path` etc*
    - *support for schema dereferencing before validation*
    - *support for multipart resources*
    - *support for csv dialects*

Repositories:

- [tableschema](https://github.com/okgreece/tableschema-r)
- [datapackage](https://github.com/okgreece/datapackage-r)

Maintainers:

- [OKI Greece](https://github.com/okgreece)

## Clojure

Requirements to implement:

- **tableschema**
    - read and validate a table schema descriptor
    - create and edit a table schema descriptor
    - provide an API to interact with a table schema descriptor
    - infer a table schema descriptor from a supplied sample of data
    - validate a data source against the table schema descriptor, including in response to editing the descriptor
    - streaming and reading of a data source through a table schema with cast on iteration
    - save a table schema descriptor to a file path
    - *cover the latest changes in the spec such as `bareNumber`, `true/falseValues`, `string PK/FK` etc*
    - *support true data streaming*
    - *support all data constraints*
    - *support all data types*
- **datapackage**
    - read and validate a data package descriptor, including profile-specific validation via the registry of JSON Schemas
    - create and edit a data package descriptor, including methods to add and remove resources and validation after editing
    - provide an API to interact with a data package descriptor
    - streaming and reading of resources through a table schema with cast on iteration
    - save a data package descriptor to a file path
    - save a data package as a zip file on disc
    - read a zip file containing a data package
    - *cover the latest changes in the specs such as string/array for `path` etc*
    - *support for schema dereferencing before validation*
    - *support for multipart resources*
    - *support for csv dialects*
    
Repositories:

- [tableschema](https://github.com/frictionlessdata/tableschema-clj)
- [datapackage](https://github.com/frictionlessdata/datapackage-clj)

Maintainers:

- [Matthew Thompson](https://github.com/cblop)

## Julia

Requirements to implement:

- **tableschema**
    - read and validate a table schema descriptor
    - create and edit a table schema descriptor
    - provide an API to interact with a table schema descriptor
    - infer a table schema descriptor from a supplied sample of data
    - validate a data source against the table schema descriptor, including in response to editing the descriptor
    - streaming and reading of a data source through a table schema with cast on iteration
    - save a table schema descriptor to a file path
    - *cover the latest changes in the spec such as `bareNumber`, `true/falseValues`, `string PK/FK` etc*
    - *support true data streaming*
    - *support all data constraints*
    - *support all data types*
- **datapackage**
    - read and validate a data package descriptor, including profile-specific validation via the registry of JSON Schemas
    - create and edit a data package descriptor, including methods to add and remove resources and validation after editing
    - provide an API to interact with a data package descriptor
    - streaming and reading of resources through a table schema with cast on iteration
    - save a data package descriptor to a file path
    - save a data package as a zip file on disc
    - read a zip file containing a data package
    - *cover the latest changes in the specs such as string/array for `path` etc*
    - *support for schema dereferencing before validation*
    - *support for multipart resources*
    - *support for csv dialects*
    
Repositories:

- [tableschema](https://github.com/frictionlessdata/tableschema-jl)
- [datapackage](https://github.com/frictionlessdata/datapackage-jl)

Maintainers:

- [Oleg Lavrovsky](https://github.com/loleg)

**Comment by roll** [comment]
cc @serahrono

**Comment by roll** [comment]
Java update:
- [x] read and validate a table schema descriptor - not supported remote descriptors - https://github.com/frictionlessdata/tableschema-java/issues/5
- [x] provide an API to interact with a table schema descriptor - fieldNames, primaryKey etc properties? - https://github.com/frictionlessdata/tableschema-java/issues/6
- [x] save a table schema descriptor to a file path - https://github.com/frictionlessdata/tableschema-java/issues/8
- [x] read and validate a table schema descriptor - not supported remote descriptors -
 https://github.com/frictionlessdata/tableschema-java/issues/5#issuecomment-335603603

**Comment by roll** [comment]
Go update:
- [x] support all data constraints - https://github.com/frictionlessdata/tableschema-go/issues/42

**Comment by roll** [comment]
@serahrono @OriHoch @georgeslabreche @danielfireman @kleanthisk10 @cblop @loleg
I think the best way for us to communicate updates will be this issue. So I've moved the hackmd document to here. I've added a few updates as examples (and updated the main issue message)

**Comment by georgeslabreche** [comment]
Regarding the follow for tableschema-java:

> Cover the latest true/falseValues changes in the spec (enhancement – [GitHub Issue #4](https://github.com/frictionlessdata/tableschema-java/issues/4)).

I have yet to convince myself on the best approach to include optional trueValues and falseValues parameters for the Field class’ constructors since the type of the Field may not always be boolean. It’s a bit awkward to have trueValues and falseValues constructor parameters for non boolean Field instanciations. Maybe creating a child class called BooleanField will be a better approach? Thoughts, anyone?

**Comment by danielfireman** [comment]
tableschema-go v1.0 released: https://github.com/frictionlessdata/tableschema-go/releases

**Comment by roll** [comment]
@danielfireman 
Great! Congratulations!

**Comment by danielfireman** [comment]
Go update: 

* ~~read and validate a data package descriptor, including profile-specific validation via the registry of JSON Schemas~~
* ~~create and edit a data package descriptor, including methods to add and remove resources and validation after editing~~
* ~~provide an API to interact with a data package descriptor~~
* ~~streaming and reading of resources through a table schema with cast on iteration~~

@roll , could you please take a look?

**Comment by roll** [comment]
@danielfireman 
Great. Thanks! I'll review in coming days (hopefully it's not blocking).

**Comment by danielfireman** [comment]
Go update:

* ~~save a data package descriptor to a file path~~
* ~~save a data package as a zip file on disc~~
* ~~read a zip file containing a data package~~
* ~~cover the latest changes in the specs such as string/array for path etc~~

**Comment by danielfireman** [comment]
Go update:

* ~~support for schema dereferencing before validation~~
* ~~support for multipart resources~~
* ~~support for csv dialects~~

All done. Ready for a complete review :smiley:

**Comment by georgeslabreche** [comment]
Java update for the **datapackage**:
- [ ] read and validate a data package descriptor, including profile-specific validation via the registry of JSON Schemas - #6
- [ ] create and edit a data package descriptor, including methods to add and remove resources and validation after editing - #7
- [ ] provide an API to interact with a data package descriptor - #8
- [ ] save a data package descriptor to a file path - #10
- [ ] save a data package as a zip file on disc - #11
- [ ] read a zip file containing a data package - #12
- [ ] support for multipart resources - #15

**Comment by roll** [comment]
@danielfireman 
@georgeslabreche 
As discussed with Daniel unfortunately I'll be able to review and commit changes to first post only on next week. For now trying to unblock everyone and looking forward for next week reviews.

**Comment by georgeslabreche** [comment]
@roll I'll just keep updating that list in the meantime.

**Comment by OriHoch** [comment]
Php update:
* tableschema: all issues  fixed
* datapackage: 
  * ~read a zip file containing a data package?~ done
  * ~support for csv dialects~ done

**Comment by danielfireman** [comment]
Hi @roll, good morning. Could you please finish the [datapackage-go](github.com/frictionlessdata/datapackage-go) review?

**Comment by roll** [comment]
@danielfireman 
Hi, unfortunately I still can't have allocated time for it.. We're considering it's done.

**Comment by Stephen-Gates** [comment]
I wonder if it would also be useful for apps that use these implementations to provide an implementation statement. e.g. Data Curator implements:

- [x] data package  (partial)
  - only tabular data packages
  - cannot add properties:
    - `homepage`
    - `image`
    - `keywords`
    - `created`
- [x] data resource (partial)
  - only tabular data packages
  - cannot add properties:
      - `data` in-line data
      - `path` data at a url
      - `bytes`
      - `hash`
- [x] tabular data package
- [x] tabular data resources (partial)
  - cannot add:
    - JSON tabular data
    - `schema` at url
    - CSV `dialect` at a url
- [x] table schema
- [ ] CSV dialect ([planned](https://github.com/ODIQueensland/data-curator/milestone/11) partial support)
  - `"delimiter"`: `,`, `;`, or `/t`
  - `"header": true`
- [x] [Data package version](https://frictionlessdata.io/specs/patterns/#data-package-version) pattern
- [ ] [Table Schema: Foreign Keys to Data Packages](https://frictionlessdata.io/specs/patterns/#table-schema:-foreign-keys-to-data-packages) pattern ([planned](https://github.com/ODIQueensland/data-curator/milestone/18))
...

Suggest this would be done at the spec level unless there is partial implementations

**Comment by roll** [comment]
High-level statuses are here now - https://github.com/frictionlessdata/software/blob/master/STATUS.md
