### ISSUE TITLE
Publish/update FrictionlessData libraries on Anaconda

### ISSUE THREAD

**Issue by zaneselvans** [frictionlessdata/implementations#34]
# Overview

We want our core libraries be available and working on Anaconda platform.

# Tasks

- [x] tabulator - https://anaconda.org/conda-forge/tabulator
- [x] tableschema - https://anaconda.org/conda-forge/tableschema
- [x] datapacakge - https://anaconda.org/conda-forge/datapackage
- [x] goodtables - https://anaconda.org/conda-forge/goodtables

---

By @zaneselvans

When attempting to create a conda environment that makes use of `tableschema` and also requires `python>=3.7`, the dependency resolution fails (see [this issue](https://github.com/frictionlessdata/tableschema-py/issues/238):

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - python[version='>=3.7']
  - tableschema
```
However, `tableschema` was just updated to use a more recent version of `tabulator` which is supposedly free of the restrictive versions (`cchardet` ???).  Nevertheless, when looking at the current set of version requirements on `tabulator` it looks like the `cchardet` requirements are still lingering:
```
Loading channels: done
tabulator 1.21.0 py_0
---------------------
file name   : tabulator-1.21.0-py_0.tar.bz2
name        : tabulator
version     : 1.21.0
build       : py_0
build number: 0
size        : 29 KB
license     : MIT
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/tabulator-1.21.0-py_0.tar.bz2
md5         : 255732fa997888f947585303f85109af
timestamp   : 2019-05-27 12:42:32 UTC
dependencies: 
  - cchardet >=1.0,<2.0
  - click >=6.0,<7.0
  - ijson >=2.0,<3.0
  - jsonlines >=1.1,<2.0
  - linear-tsv >=1.0,<2.0
  - openpyxl >=2.4,<2.5
  - python
  - requests >=2.8,<3.0
  - six >=1.9,<2.0
  - sqlalchemy >=0.9.6,<2.0
  - unicodecsv >=0.14,<2.0
  - xlrd >=1.0,<2.0
```
Even though the `[setup.py](https://github.com/frictionlessdata/tabulator-py/blob/master/setup.py)` for `tabulator-py` does not include those restrictive `cchardet` versions.  I feel like I must not really understand how these dependencies are specified and propagate.

**Comment by roll** [comment]
I'm also having a try to publish `goodtables` here - https://github.com/conda-forge/staged-recipes/pull/8532

**Comment by ocefpaf** [comment]
> I'm not sure how Anaconda packaging works. It seems kinda half-automated regarding new versions. But should I PR this file [conda-forge/tabulator-feedstock:recipe/meta.yaml@`master`](https://github.com/conda-forge/tabulator-feedstock/blob/master/recipe/meta.yaml) [](/conda-forge/tabulator-feedstock/blob/HEAD@{2019-06-24T07:41:37Z}/recipe/meta.yaml) to update dependencies?

Yep. Also, if you open issue there it will be easier for me to see/action on them.

**Comment by roll** [comment]
@ocefpaf 
I've created the issues:
- https://github.com/conda-forge/tableschema-feedstock/issues/16
- https://github.com/conda-forge/datapackage-feedstock/issues/9

If you'd like I can PR also but it seems I need to install some conda software first

**Comment by roll** [comment]
@zaneselvans 
@cmgosnell
Could you please take a look, all our main libs should be now available on Anaconda Cloud and working.

cc @lwinfree

**Comment by zaneselvans** [comment]
Yep! It all seems to be working now.  I've updated our `environment.yml` to pull them with `conda` instead of `pip`. Now we just have one more `pip` based package left, and it will go away when we replace postgres with the datapackage outputs.
