### ISSUE TITLE
Rebase on auto security tracking by Github

### ISSUE THREAD

**Issue by roll** [frictionlessdata/implementations#39]
# Overview

Github now helps us to watch security. With new automation, we don't need to follow it manually after this issue is closed.

# Tasks

- [x] enable auto security fixes for all the repos
- [x] fix all the previous found security issues (before auto fixes)
- [ ] fix goodtables.io security issues - https://github.com/frictionlessdata/goodtables.io/pull/337

**Comment by roll** [comment]
DONE

will handle goodtables.io separately
