### ISSUE TITLE
Put in order javascript libraries

### ISSUE THREAD

**Issue by roll** [frictionlessdata/implementations#9]
# Overview

We have many javascript libraries - https://github.com/frictionlessdata?language=javascript&q=&type=&utf8=%E2%9C%93

- some of them should be deprecated after `datapackage-js` will be ready (merged)
- not merged ones should be better described with some docs in readme

# Tasks

- [x] deprecate `datapackage-registry-js` (`datapackage.Profiles`)
- [x] deprecate `datapackage-validate-js` (`datapackage.validate`)
- [x] `datapackage-identifier-js` - https://github.com/frictionlessdata/datapackage-js/issues/21 (removed by someone)
- [x] `datapackage-init-js` - https://github.com/frictionlessdata/datapackage-js/issues/15 (removed by someone)
- [x] `datapackage-from-remote-js` (removed by someone)
- [x] `datapackage-read-js` (removed by someone)
- [x] `datapackage-outfile-js` (removed by someone)
- [x] `datapackage-ckan-js` (removed by someone)
- [x] `jsontableschema-openrefine-py` (experimental)
